http:
  middlewares:
    homelab-auth-token:
      headers:
        # adds headers to requests going FROM Traefik TO the services sitting behind it
        # customRequestHeaders:
        #   X-Homelab-Auth-Test: ""
        # adds headers to responses going FROM services behind traefik back TO clients
        # customResponseHeaders:
        #   X-Homelab-Auth-Token: ""
