---
- homelab:
    - router web ui:
        - abbr: GLiNet
          href: http://192.168.8.1
    - pve web ui:
        - icon: proxmox.png
          href: "{{{@pve.endpoint}}}"
    - edsac pbs:
        - abbr: PBS
          href: "{{{SECRET_EDSAC_PBS_URL}}}"
    - cloud pbs:
        - abbr: PBS
          href: "{{{SECRET_CLOUD_PBS_URL}}}"
    - home labs slack:
        - icon: slack.png
          href: "{{{SECRET_SLACK_WEBUI_URL}}}"
    - home labs pushover:
        - icon: pushover.png
          href: https://client.pushover.net
    - pangolin:
        - icon: pangolin.png
          href: https://pangolin.minch.zone
- etc:
    - HaC Github:
        - abbr: HaC
          href: https://github.com/minchingtonak/HaC
    - pulumi cloud homelab:
        - abbr: Pu
          href: https://app.pulumi.com/minchingtonak/HaC/homelab/updates
    - slack api:
        - icon: slack.png
          href: https://api.slack.com/apps/
    - nextcloud:
        - icon: nextcloud.png
          href: "{{{SECRET_NEXTCLOUD_URL}}}"
    - healthchecksio:
        - icon: healthchecks.png
          href: https://healthchecks.io
    - pushover:
        - icon: pushover.png
          href: https://pushover.net
