hostname = "archiver"
description = "worker for archive team warrior"

[stacks]
traefik = {}
dozzle = {}
archiveteam-warrior = {}
# ytptube = {}

[cpu]
cores = 2

[memory]
dedicated = 4096
swap = 2048

[disk]
size = 8

[[mount_points]]
volume = "{{{@pve.lxc.app_data_dir}}}/archiver"
mount_point = "/docker"

[[mount_points]]
volume = "{{{@pve.storage.mass.path}}}/podcasts"
mount_point = "/mnt/podcasts"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-periphery.sh"
