hostname = "immich"
description = "private image server"

[stacks]
traefik = {}
dozzle = {}
immich = {}

[cpu]
cores = 2

[memory]
dedicated = 4096
swap = 2048

[disk]
size = 64

[[mount_points]]
volume = "{{{@pve.lxc.app_data_dir}}}/immich"
mount_point = "/docker"

[[mount_points]]
volume = "/void/photos"
mount_point = "/mnt/photos"

[[mount_points]]
volume = "/void/drive"
mount_point = "/mnt/drive"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/configure-apparmor-unconfined.yaml"
replayable = false

[provisioners.variables]
lxc_id = "{{{idForContainer hostname='immich'}}}"

[provisioners.connection]
host = "{{{@pve.ip}}}"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
