hostname = "life"
description = "life tracking apps"

[stacks]
traefik = {}
dozzle = {}
mealie = {}
tandoor-recipes = {}
cleanslate = {}
fittrackee = {}
wallos = {}
dawarich = {}
trip = {}
memos = {}

[cpu]
cores = 4

[memory]
dedicated = 8192
swap = 4096

[disk]
size = 32

[[mount_points]]
volume = "{{{@pve.lxc.app_data_dir}}}/life"
mount_point = "/docker"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
