hostname = "music"
description = "assorted audio management apps"
start_on_boot = true

[stacks]
traefik = {}
dozzle = {}
audiobookshelf = {}
navidrome = {}
picard = {}
sonobarr = {}
your-spotify = {}
spotizerr = {}

[cpu]
cores = 2

[memory]
dedicated = 8192
swap = 4096

[disk]
size = 16

[[mount_points]]
volume = "{{{@pve.lxc.app_data_dir}}}/music"
mount_point = "/docker"

[[mount_points]]
volume = "/void/audiobooks"
mount_point = "/mnt/audiobooks"

[[mount_points]]
volume = "/void/media"
mount_point = "/mnt/media"

[[mount_points]]
volume = "/void/podcasts"
mount_point = "/mnt/podcasts"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/configure-apparmor-unconfined.yaml"
replayable = false

[provisioners.variables]
lxc_id = "{{{idForContainer hostname='music'}}}"

[provisioners.connection]
host = "{{{@pve.ip}}}"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
