hostname = "paperless"
description = "paperless document management systems"

[stacks]
traefik = {}
dozzle = {}
paperless-ngx = {}

[cpu]
cores = 8

[memory]
dedicated = 8192
swap = 4096

[disk]
size = 16

[[mount_points]]
volume = "{{{@pve.lxc.app_data_dir}}}/paperless"
mount_point = "/docker"

[[mount_points]]
volume = "/void/documents"
mount_point = "/mnt/documents"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
