hostname = "tools"
description = "swiss army knife of utility tools"

[stacks]
traefik = {}
dozzle = {}
cyberchef = {}
docuseal = {}
stirling-pdf = {}
bentopdf = {}
it-tools = {}
omni-tools = {}
mazanoke = {}
withoutbg = {}

[cpu]
cores = 4

[memory]
dedicated = 8192
swap = 4096

[disk]
size = 16

[[mount_points]]
volume = "{{{@pve.lxc.app_data_dir}}}/tools"
mount_point = "/docker"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
