hostname = "windmill"
description = "windmill code-first automation platform, mostly used for spotify automation"

[stacks]
traefik = {}
dozzle = {}
windmill = {}
archiveteam-warrior = {}

[cpu]
cores = 2

[memory]
dedicated = 4096
swap = 2048

[disk]
size = 64

[[mount_points]]
volume = "{{{@pve.lxc.app_data_dir}}}/windmill"
mount_point = "/docker"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/configure-apparmor-unconfined.yaml"
replayable = false

[provisioners.variables]
lxc_id = "{{{idForContainer hostname='windmill'}}}"

[provisioners.connection]
host = "{{{@pve.ip}}}"

[[provisioners]]
type = "ansible"
playbook = "provisioners/ansible/lxc-init.yaml"
replayable = false

[[provisioners]]
type = "script"
script = "provisioners/scripts/install-docker.sh"
