node = "homelab"
endpoint = "https://192.168.8.89:8006"
ip = "192.168.8.89"
domain = "akmin.dev"

[auth]
username = "{{{SECRET_USERNAME}}}"
password = "{{{SECRET_PASSWORD}}}"
insecure = true

[ssh]
user = "{{{SECRET_SSH_USER}}}"
public_key = "{{{SECRET_CONTAINER_SSH_PUBLIC_KEY}}}"
private_key = """{{{SECRET_CONTAINER_SSH_PRIVATE_KEY}}}"""

[storage]
mass = { name = "void", path = "/void" }
fast = { name = "fast", path = "/fast" }

[[files]]
datastore_id = "local"
content_type = "vztmpl"
# http://download.proxmox.com/images/system/
url = "http://download.proxmox.com/images/system/debian-13-standard_13.1-2_amd64.tar.zst"
checksum = "5aec4ab2ac5c16c7c8ecb87bfeeb10213abe96db6b85e2463585cea492fc861d7c390b3f9c95629bf690b95e9dfe1037207fc69c0912429605f208d5cb2621f8"
checksum_algorithm = "sha512"
overwrite_unmanaged = true
retain_on_delete = true

[lxc]
app_data_dir = "/fast/appdata"

[lxc.hosts]
jellyfin = { id = 203 }
immich = { id = 207 }
paperless = { id = 214 }
life = { id = 215 }
tools = { id = 208 }
music = { id = 216 }
servarr = { id = 201 }
gameserver = { id = 210 }
admin = { id = 213 }
backup = { id = 202 }
windmill = { id = 209 }
syncthing = { id = 212 }

[lxc.network]
domain = "akmin.dev"
subnet = "192.168.8"
gateway = "192.168.8.1"

[lxc.auth]
password = "{{{SECRET_CONTAINER_ROOT_PASSWORD}}}"

[lxc.ssh]
user = "{{{SECRET_CONTAINER_SSH_USER}}}"
public_key = "{{{SECRET_CONTAINER_SSH_PUBLIC_KEY}}}"
private_key = """{{{SECRET_CONTAINER_SSH_PRIVATE_KEY}}}"""

[providers.dns.porkbun]
api_key = "{{{SECRET_PORKBUN_API_KEY}}}"
secret_key = "{{{SECRET_PORKBUN_SECRET_KEY}}}"
