global_keywords:
  keywords:
    - foo
# loggifly requires at least one container to be defined here
containers:
  "{{{@lxc.hostname}}}-dummy-container":
notifications:
  apprise:
    # Any Apprise-compatible URL (https://github.com/caronc/apprise/wiki)
    url: "pover://{{{pushover:SECRET_USER_TOKEN}}}@{{{loggifly:SECRET_PUSHOVER_TOKEN}}}?priority=normal"
